# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170130_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
